-- CREATE TABLE SALESMAN(
-- SALESMAN_ID VARCHAR(40) NOT NULL,
-- NAME_ VARCHAR(40) NOT NULL,
-- CITY_ VARCHAR(40) NOT NULL,
-- COMISSION FLOAT(2) NOT NULL
-- );
INSERT INTO SALESMAN VALUES(2001,"ABHI","PUNE",0.15),(2002, "ARJUN","MUMBAI",0.16),(2003,"RAM","DELHI",0.15);
SELECT * FROM SALESMAN;

